### ISSUE TITLE
Don't use a port in the ephemeral range (35729)

### ISSUE THREAD

**Issue by sglajchEG** [livereload/livereload-js#90]
It seems that this service uses the 35729 port statically.  That is you can't run two versions of this service at the same time because (unless the caller of the service specifies, which most don't), it will attempt to re-use the same port.

For instance I'm using this from a grunt plugin (https://github.com/gruntjs/grunt-contrib-watch), and grunt calls it without a port parameter, which makes it have the same port each time.

If you're going to have a static port, you need to define it in the range of non-ephemeral ports.  For instance in Linux the ephemeral port range is 32768-61000.  These ports are used for programs to bind port numbers that can change each time, typically for internal uses.  What this means is that by statically attempting to bind a port in this range, you might not always be able to get the port, and you might be at risk of breaking other programs.

For now I'd recommend you just use a different port for livereload-js by default.

**Comment by smhg** [comment]
Am I right that is first of all related to LiveReload server implementations? Or at least a project-wide discussion.
In both cases, since this repo is for the JS client only, this shouldn't be discussed here. Because of that, I'm closing this. But please feel free to bring this up in the appropriate place.
