### ISSUE TITLE
[enhancement] Publish latest @rollup plugin

### ISSUE THREAD

**Issue by dmgolembiowski** [livereload/livereload-js#95]
NPM suggested that I reach out to the livereload repository with the following suggestion:

```bash
 $ npm install --save-dev @rollup/plugin-livereload
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rollup%2fplugin-livereload - Not found
npm ERR! 404 
npm ERR! 404  '@rollup/plugin-livereload@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
Rollup is probably responsible for the npm packaging but there may be some required coordinating with livereload efforts at [the issue page](https://github.com/rollup/plugins/issues/383).

**Comment by smhg** [comment]
Hi @dmgolembiowski! I suggest someone reaches out when there is a specific question about the livereload-js package that needs to be addressed to enable the rollup-plugin. Since it doesn't seem to exist yet, there is no need to have an issue open in this repo.
Feel free to open a new issue if such questions arise.
